### ISSUE TITLE
labels for custom dataset when using Object-Detector-App 

### ISSUE THREAD

**Issue by lhammond** [datitran/raccoon-dataset#4]
with a custom dataset that has a single class, should I create a new .pbtxt file in object_detection/data that has my class, then change the line in object_detection_app.py to point to my new file?

`# List of the strings that is used to add correct label for each box.
PATH_TO_LABELS = os.path.join(CWD_PATH, 'object_detection', 'data', 'mscoco_label_map.pbtxt')
`

`# List of the strings that is used to add correct label for each box.
PATH_TO_LABELS = os.path.join(CWD_PATH, 'object_detection', 'data', 'my_custom_labels.pbtxt')
`

**Comment by datitran** [comment]
Yes you should as the label map is used to show the classes while running the app.
