### ISSUE TITLE
generate_tfrecord.py is broken

### ISSUE THREAD

**Issue by oscarorti** [datitran/raccoon-dataset#5]
Hi @datitran ,
I tried the generate_tfrecord.py script, and I think that something goes wrong, because I've printed all variables to save just before save it and I get this for all images: 

print(filename, xmins, ymins, xmaxs, ymaxs)

('raccoon-193.jpg', [0], [0], [0], [0])
('raccoon-138.jpg', [0], [0], [0], [0])
('raccoon-157.jpg', [0], [0], [0], [0])
('raccoon-108.jpg', [0], [0], [0], [0])
('raccoon-116.jpg', [0], [0], [0], [0])
('raccoon-117.jpg', [0], [0], [0], [0])
('raccoon-117.jpg', [0], [0], [0], [0])
('raccoon-12.jpg', [0], [0], [0], [0])

This could be in the normalization process that considers integers instead of floats, is it possible?
Thanks!

PD: did you use this script to generate your tfrecord files?

**Comment by datitran** [comment]
Yes I did use this script, otherwise it wouldn't be there;) This is what you should get:

```
b'raccoon-17.jpg' [0.3667953667953668] [0.6447876447876448] [0.30927835051546393] [0.6082474226804123]
b'raccoon-11.jpg' [0.004545454545454545] [0.6984848484848485] [0.0023148148148148147] [0.9976851851851852]
b'raccoon-63.jpg' [0.12333333333333334] [0.4666666666666667] [0.2675] [0.725]
b'raccoon-63.jpg' [0.37833333333333335] [0.6716666666666666] [0.2325] [0.745]
b'raccoon-60.jpg' [0.21245421245421245] [0.7216117216117216] [0.1783783783783784] [0.6864864864864865]
b'raccoon-69.jpg' [0.05853658536585366] [0.9170731707317074] [0.044715447154471545] [0.975609756097561]
b'raccoon-180.jpg' [0.19833333333333333] [0.6133333333333333] [0.0525] [0.9975]
...
```

What python version are you using? There are some problems with 2.7 that others told me. Try to use the same dependencies as in the `environment.yml` file.

**Comment by oscarorti** [comment]
Yes, sorry!
It goes ok! It was the python version, I was using 2.7.

Thanks!
