### ISSUE TITLE
TFRecord error

### ISSUE THREAD

**Issue by Futi7** [datitran/raccoon-dataset#85]
C:\Users\Fuat\Desktop\raccoon_dataset-master>python generate_tfrecord.py --csv_input=data/train_labels.csv --output_path=train.record
Traceback (most recent call last):
File "generate_tfrecord.py", line 100, in 
tf.app.run()
File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
_sys.exit(main(argv))
File "generate_tfrecord.py", line 91, in main
tf_example = create_tf_example(group, path)
File "generate_tfrecord.py", line 46, in create_tf_example
encoded_jpg = fid.read()
File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 125, in read
self._preread_check()
File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 85, in _preread_check
compat.as_bytes(self.__name), 1024 * 512, status)
File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in exit
c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: raccoon-179.jpg : Sistem belirtilen dosyay\udcfd bulam\udcfdyor.
; No such file or directory

I don't know what is the problem i searched for a solution but couldn't find any.Can anyone help me please?

**Comment by aniketbote** [comment]
1) Add new flag
**flags.DEFINE_string('image_path', '', 'Path to images')**

2) Replace path = os.path.join(os.getcwd(), 'images') in main
with **path = os.path.join(os.getcwd(), FLAGS.image_path)**

3) Run it
python3 generate_tfrecord.py --csv_input=data/train_labels.csv --output_path=data/train.record **--image_path=images/train**﻿

**Comment by Futi7** [comment]
C:\Users\Fuat\Desktop\dataset>python generate_tfrecord.py --csv_input=data/futi_labels.csv --output_path=data/train.record --image_dir=images
Traceback (most recent call last):
  File "generate_tfrecord.py", line 102, in <module>
    tf.app.run()
  File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "generate_tfrecord.py", line 93, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 48, in create_tf_example
    encoded_jpg = fid.read()
  File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 125, in read
    self._preread_check()
  File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: images\raccoon-149.jpg.jpg : Sistem belirtilen dosyayi bulamiyor.
; No such file or directory

---------------------------------

Yes i tried that too this error shows up.

**Comment by LuciousZhang** [comment]
> C:\Users\Fuat\Desktop\dataset>python generate_tfrecord.py --csv_input=data/futi_labels.csv --output_path=data/train.record --image_dir=images
> Traceback (most recent call last):
> File "generate_tfrecord.py", line 102, in 
> tf.app.run()
> File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
> _sys.exit(main(argv))
> File "generate_tfrecord.py", line 93, in main
> tf_example = create_tf_example(group, path)
> File "generate_tfrecord.py", line 48, in create_tf_example
> encoded_jpg = fid.read()
> File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 125, in read
> self._preread_check()
> File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 85, in _preread_check
> compat.as_bytes(self.__name), 1024 * 512, status)
> File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in **exit**
> c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: images\raccoon-149.jpg.jpg : Sistem belirtilen dosyayi bulamiyor.
> ; No such file or directory
> 
> Yes i tried that too this error shows up.

be sure the file **images** in your current workspace with **generate_tfrecord.py**
```
python generate_tfrecord.py --csv_input=insulator.csv --output_path=insulator_test.record --image_dir=images
```

**Comment by harshaldeore7** [comment]
> C:\Users\Fuat\Desktop\dataset>python generate_tfrecord.py --csv_input=data/futi_labels.csv --output_path=data/train.record --image_dir=images
> Traceback (most recent call last):
> File "generate_tfrecord.py", line 102, in 
> tf.app.run()
> File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
> _sys.exit(main(argv))
> File "generate_tfrecord.py", line 93, in main
> tf_example = create_tf_example(group, path)
> File "generate_tfrecord.py", line 48, in create_tf_example
> encoded_jpg = fid.read()
> File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 125, in read
> self._preread_check()
> File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 85, in _preread_check
> compat.as_bytes(self.__name), 1024 * 512, status)
> File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in **exit**
> c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: images\raccoon-149.jpg.jpg : Sistem belirtilen dosyayi bulamiyor.
> ; No such file or directory
> 
> Yes i tried that too this error shows up.

- copy all test images to **images** folder instead of **test** folder in **images** folder
- remove that '**test**' folder from that images folder
- in **images** folder only the test images should be there nothing else
- run that
**python generate_tfrecord.py --csv_input=data/train_labels.csv  --output_path=train.record**

- do the same thing for test images and run
 python generate_tfrecord.py --csv_input=data/train_labels.csv --output_path=data/train.record --image_path=images/train﻿
